DROP SCHEMA IF EXISTS WishList;
CREATE SCHEMA IF NOT EXISTS WishList;
USE WishList;

DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS WishlistProducts;
DROP TABLE IF EXISTS WishlistUsers;
DROP TABLE IF EXISTS Wishlists;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Sessions;

CREATE TABLE IF NOT EXISTS Users (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(64),
    Username TEXT,
    Password TEXT
);

CREATE TABLE IF NOT EXISTS Wishlists (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    AuthorID INT,
    Title TEXT,
    HeldOn DATETIME,
    FOREIGN KEY (AuthorID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Products (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Title TEXT,
    Price DOUBLE,
    Manufacturer TEXT,
    PathToImage VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS WishlistProducts (
	WishlistID INT,
    ProductID INT,
    Reserved BOOL,
    PRIMARY KEY (WishlistID, ProductID),
    FOREIGN KEY (WishlistID) REFERENCES Wishlists(ID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WishlistGuests (
	WishlistID INT,
    UserID INT,
	PRIMARY KEY (WishlistID, UserID),
    FOREIGN KEY (WishlistID) REFERENCES Wishlists(ID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Sessions (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    ActivatedOn DATETIME,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);